# Generated by Django 4.2.19 on 2025-02-28 01:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('sale_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Id')),
                ('total_price', models.IntegerField()),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
        migrations.CreateModel(
            name='Sales_Detail',
            fields=[
                ('sale_detail', models.AutoField(primary_key=True, serialize=False, verbose_name='Id')),
                ('amount', models.IntegerField()),
                ('price', models.IntegerField()),
                ('plant_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventory.plant', verbose_name='Plant')),
                ('sale_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sales.sale', verbose_name='Sale')),
            ],
        ),
    ]
