# Generated by Django 4.2.19 on 2025-02-28 01:06

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Id')),
                ('category', models.CharField(max_length=30, verbose_name='Category')),
            ],
        ),
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('plant_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Id')),
                ('plant_name', models.CharField(max_length=30, verbose_name='Plant Name')),
                ('care', models.CharField(max_length=1000, verbose_name='Care')),
                ('price', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Price')),
                ('stock', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Stock')),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventory.categorie', verbose_name='Categorie')),
            ],
        ),
    ]
